/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cacacodigo;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 22.00388-6
 */
public class LoginForm extends javax.swing.JFrame{

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        super("Caça-Código");
        initComponents();
        lbConfirmarSenha.setVisible(false);
        confirmarSenha.setVisible(false);
        
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelHeader = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PainelBanner = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PainelForm = new javax.swing.JPanel();
        TextSenha = new javax.swing.JLabel();
        TextParaContinuar = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JLabel();
        campoUser = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoLogin = new javax.swing.JButton();
        lbHyperLink = new javax.swing.JLabel();
        hyperLinkCadastro = new javax.swing.JLabel();
        lbConfirmarSenha = new javax.swing.JLabel();
        confirmarSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelHeader.setBackground(new java.awt.Color(1, 27, 16));

        jLabel9.setFont(new java.awt.Font("Courier 10 Pitch", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Caça-Código");

        javax.swing.GroupLayout PainelHeaderLayout = new javax.swing.GroupLayout(PainelHeader);
        PainelHeader.setLayout(PainelHeaderLayout);
        PainelHeaderLayout.setHorizontalGroup(
            PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHeaderLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelHeaderLayout.setVerticalGroup(
            PainelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHeaderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cacacodigo/Sem título(1).jpg"))); // NOI18N

        javax.swing.GroupLayout PainelBannerLayout = new javax.swing.GroupLayout(PainelBanner);
        PainelBanner.setLayout(PainelBannerLayout);
        PainelBannerLayout.setHorizontalGroup(
            PainelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelBannerLayout.setVerticalGroup(
            PainelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TextSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextSenha.setText("Senha:");

        TextParaContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextParaContinuar.setText("Para continuar entre na sua conta:");

        TextUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextUsuario.setText("Usuário:");

        campoUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        botaoLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoLogin.setText("Fazer Login");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        lbHyperLink.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHyperLink.setText("Não possui login?");

        hyperLinkCadastro.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        hyperLinkCadastro.setForeground(new java.awt.Color(51, 51, 255));
        hyperLinkCadastro.setText("Cadastrar!");
        hyperLinkCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hyperLinkCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hyperLinkCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hyperLinkCadastroMouseExited(evt);
            }
        });

        lbConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbConfirmarSenha.setText("Confirmar Senha:");

        confirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout PainelFormLayout = new javax.swing.GroupLayout(PainelForm);
        PainelForm.setLayout(PainelFormLayout);
        PainelFormLayout.setHorizontalGroup(
            PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFormLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbHyperLink)
                .addGap(18, 18, 18)
                .addComponent(hyperLinkCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFormLayout.createSequentialGroup()
                        .addComponent(botaoLogin)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFormLayout.createSequentialGroup()
                        .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelFormLayout.createSequentialGroup()
                                .addComponent(lbConfirmarSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(confirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelFormLayout.createSequentialGroup()
                                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextUsuario)
                                    .addComponent(TextSenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(90, 90, 90))))
            .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFormLayout.createSequentialGroup()
                    .addContainerGap(113, Short.MAX_VALUE)
                    .addComponent(TextParaContinuar)
                    .addGap(93, 93, 93)))
        );
        PainelFormLayout.setVerticalGroup(
            PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFormLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextUsuario))
                .addGap(31, 31, 31)
                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSenha)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmarSenha)
                    .addComponent(confirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHyperLink)
                    .addComponent(hyperLinkCadastro))
                .addGap(45, 45, 45))
            .addGroup(PainelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelFormLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(TextParaContinuar)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PainelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PainelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
       if (botaoLogin.getText().equals("Cadastrar")){
           // se o campo usuario estiver vazio ****************************
           if (campoUser.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Digite o nome de usuário", "Erro", JOptionPane.ERROR_MESSAGE);
           }
           else{
               // Se os campos senhas e usuario estiverem ok
                if (campoSenha.getText().equals("") == false && campoSenha.getText().equals(confirmarSenha.getText())){
                    // Se senha for muito curta
                    if (campoSenha.getText().length() < 5){
                        JOptionPane.showMessageDialog(null, "Senha deve conter pelo menos 5 caracteres", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        // Realiza o cadastro do usuario se ele nao ja estiver cadastrado
                        Banco bd = new Banco(ConnFactory.conectar());
                        if (bd.verificarUsuario(campoUser.getText())){
                            JOptionPane.showMessageDialog(null, "Nome de usuário já está em uso.", "Erro", JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            // Cadastra o usuario
                            String usuario = campoUser.getText();
                            String senha = campoSenha.getText();
                            
                            if (bd.cadastrarUsuario(usuario, senha)){
                                bd.cadastrarPontuacao(usuario, 0, "99:99");
                                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
                                lbConfirmarSenha.setVisible(false);
                                confirmarSenha.setVisible(false);
                                botaoLogin.setText("Fazer Login");
                                hyperLinkCadastro.setText("Cadastrar!");
                                lbHyperLink.setText("Não possui login?");
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Erro ao cadastrar usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        
                    }
                }
                   else{
                   JOptionPane.showMessageDialog(null, "Senha inválida");
                }
           }
       }
       else{
            Banco bd = new Banco(ConnFactory.conectar());
       
            if (bd.logarUsuario(campoUser.getText(), campoSenha.getText())){
                // Inicia o jogo
                ConnFactory.desconectar(bd.getConn());
                dispose();
                Janela j = new Janela(campoUser.getText());
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void hyperLinkCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hyperLinkCadastroMouseClicked
        if (hyperLinkCadastro.getText().equals("Cadastrar!")){
            lbConfirmarSenha.setVisible(true);
            confirmarSenha.setVisible(true);
            botaoLogin.setText("Cadastrar");
            hyperLinkCadastro.setText("Logar!");
            lbHyperLink.setText("Já possui cadastro?");
        }
        else{
            lbConfirmarSenha.setVisible(false);
            confirmarSenha.setVisible(false);
            botaoLogin.setText("Fazer Login");
            hyperLinkCadastro.setText("Cadastrar!");
            lbHyperLink.setText("Não possui login?");
        }
    }//GEN-LAST:event_hyperLinkCadastroMouseClicked

    private void hyperLinkCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hyperLinkCadastroMouseEntered
        hyperLinkCadastro.setForeground(Color.RED);
    }//GEN-LAST:event_hyperLinkCadastroMouseEntered

    private void hyperLinkCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hyperLinkCadastroMouseExited
        hyperLinkCadastro.setForeground(new Color(51,51,255));
    }//GEN-LAST:event_hyperLinkCadastroMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBanner;
    private javax.swing.JPanel PainelForm;
    private javax.swing.JPanel PainelHeader;
    private javax.swing.JLabel TextParaContinuar;
    private javax.swing.JLabel TextSenha;
    private javax.swing.JLabel TextUsuario;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUser;
    private javax.swing.JPasswordField confirmarSenha;
    private javax.swing.JLabel hyperLinkCadastro;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbConfirmarSenha;
    private javax.swing.JLabel lbHyperLink;
    // End of variables declaration//GEN-END:variables
}
