/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cacacodigo;


import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author 22.00077-0
 */
public class TelaEscolha extends javax.swing.JFrame {

    /**
     * Creates new form TelaADM
     */
    private String usuario;
    
    public TelaEscolha(String usuario) {
        super("Caça-Código");
        
        this.usuario = usuario;
        
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btplacar = new javax.swing.JButton();
        btjogar = new javax.swing.JButton();
        configbot = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btplacar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btplacar.setText("PLACAR");
        btplacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btplacarActionPerformed(evt);
            }
        });
        getContentPane().add(btplacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 230, 50));
        btplacar.setBackground(Color.WHITE);

        btjogar.setBackground(new java.awt.Color(0, 0, 0));
        btjogar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btjogar.setForeground(new java.awt.Color(255, 255, 255));
        btjogar.setText("JOGAR");
        btjogar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btjogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjogarActionPerformed(evt);
            }
        });
        getContentPane().add(btjogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 230, 50));

        configbot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cacacodigo/mini smurf.png"))); // NOI18N
        configbot.setText("jLabel2");
        configbot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configbotMouseClicked(evt);
            }
        });
        getContentPane().add(configbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cacacodigo/nos.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btjogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjogarActionPerformed
        dispose();
        Janela j = new Janela(usuario);
    }//GEN-LAST:event_btjogarActionPerformed

    private void btplacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btplacarActionPerformed
        Banco bd = new Banco(ConnFactory.conectar());
        String dados[][] = bd.gerarPlacar();
        ConnFactory.desconectar(bd.getConn());
        dispose();
        TelaScore ts = new TelaScore(dados, usuario);
    }//GEN-LAST:event_btplacarActionPerformed

    private void configbotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configbotMouseClicked
        Banco bd = new Banco(ConnFactory.conectar());
        boolean adm = bd.validarAdmin(usuario);
        ConnFactory.desconectar(bd.getConn());
        
        if (adm){
            dispose();
            Configadm cfg = new Configadm(usuario);
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão de administrador para usar este recurso.");
        }
        
        
    }//GEN-LAST:event_configbotMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btjogar;
    private javax.swing.JButton btplacar;
    private javax.swing.JLabel configbot;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
