/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cacacodigo;

import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;
import javax.swing.plaf.basic.BasicScrollBarUI;
import java.awt.Color;
import static java.awt.Color.*;



/**
 *
 * @author 22.00077-0
 */

public class TelaScore extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaScore
     * 
     * 
     */
    
    private String usuario;
    
    public TelaScore(String[][] dados, String usuario) {
        super("Caça-Código");
        
        setUsuario(usuario);
        
        initComponents();
        
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new Color(255, 255, 255, 90));
        
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewportBorder(null);
        
        
        jPanel1.setBackground(new Color(0,0,0,90));
        jLabel2.setBorder(BorderFactory.createMatteBorder(3, 3, 0, 3, BLACK));
        
        jScrollPane1.setBorder(BorderFactory.createMatteBorder(0, 3, 3, 3, BLACK));
        jScrollPane1.getVerticalScrollBar().setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, GRAY));
        
        jScrollPane1.getVerticalScrollBar().setBackground(new Color(0, 0, 0));
        /*
        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = Color.GRAY;
            }
        });
        */
        
        jTextArea1.setText(formatarPlacar(dados));
        
        setVisible(true);
        
        
    
    }
    
    public void setUsuario(String usuario){
        this.usuario = usuario;
    }
    public String getUsuario(){
        return this.usuario;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMenu = new javax.swing.JToggleButton();
        jogarNovamente = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 90, 30));

        jogarNovamente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jogarNovamente.setText("Jogar novamente");
        jogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(jogarNovamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 170, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("a\na\na\na\na\na\na\na\na\na\na");
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 680, 340));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 680, 340));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Posição:                 Nome:                       Pontos:                             Tempo:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 680, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cacacodigo/parabens-removebg-preview.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cacacodigo/smurf.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        som();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarNovamenteActionPerformed
        dispose();
        Janela j = new Janela(getUsuario());
    }//GEN-LAST:event_jogarNovamenteActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        dispose();
        TelaEscolha tl = new TelaEscolha(usuario);
    }//GEN-LAST:event_btMenuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    private void som(){
        try{
            File som = new File("src\\wav\\lalalalaaaaa.wav");
            Clip c = AudioSystem.getClip();
            c.open(AudioSystem.getAudioInputStream(som));
            c.start();
        }catch(Exception e){
            ;
        }
    }
    
    // String com dados para colocar no placar ******************
    
    public String formatarPlacar(String[][] dados){
        String data = "    ";
        outerLoop : for (int i = 0; i < 100; i++){
            for (int j = 0; j < 4; j++){
                if (dados[i][j] == null){
                    break outerLoop;
                }
                switch (j){
                    case 0:
                        data += padronizarString(dados[i][j], 4) + "\t\t";
                        break;
                    case 3:
                        data += padronizarString(dados[i][j], 20) + "\n    ";
                        break;
                    default:
                        data += padronizarString(dados[i][j], 20) + "\t";
                }

            }
        }
        return data;
        
    }
    
    // **********************************************************
    
    // deixa a string com o tamanho 20 para ajustar no placar
    public String padronizarString(String texto, int tamanho) {
    int tamanhoDesejado = tamanho;
    if (texto.length() < tamanhoDesejado) {
        return String.format("%-" + tamanhoDesejado + "s", texto);
    }
    return texto;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jogarNovamente;
    // End of variables declaration//GEN-END:variables

}
